# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/buildpack-deps
#      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

#    environment:
#      # Customize the JVM maximum heap limit
#      JVM_OPTS: -Xmx1024m
#      TERM: dumb
    
    steps:
      - run:
          command: |
            echo "deb http://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
            sudo apt-get update
#            sudo apt-get apt-transport-https
            sudo apt-get install openjdk-8-jdk
            sudo apt-get install sbt
      - checkout
      - run:
          command: |
            git submodule sync
            git submodule update --init --recursive


      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "build.sbt" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-

      - run: make +clean +compile

      - save_cache:
          paths:
            - ~/.ivy2
            - ~/repo
          key: v1-dependencies--{{ checksum "build.sbt" }}

  test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image: circleci/buildpack-deps

    working_directory: ~/repo

#    environment:
#      # Customize the JVM maximum heap limit
#      JVM_OPTS: -Xmx1024m
#      TERM: dumb
        
    steps:
      - restore_cache:
          key: v1-dependencies--{{ checksum "build.sbt" }}
      # run tests!
      - run: make +test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
