# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: ucbjrl/chisel3-ci
      - user: chisel
    working_directory: ~/src/chisel-release

    environment:
      - PATH: "/opt/verilator/verilator_3_904/bin:$PATH"
      
    steps:
      # Download and cache dependencies
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout
      - run:
          command: |
            git submodule sync
            git submodule update --init --recursive

      - run: make +clean +compile

      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.sbt
            - ~/src/chisel-release
          key: source-v1-{{ .Branch }}-{{ .Revision }}

  test:
    docker:
      # specify the version you desire here
      - image: ucbjrl/chisel3-ci
      - user: chisel

    working_directory: ~/src/chisel-release

    environment:
      - PATH: "/opt/verilator/verilator_3_904/bin:$PATH"
        
    steps:
      - run: make +test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
