name: CI

on: [push]

jobs:
  build:

    container:
      image: ucbbar/chisel3-tools
      options: --user root --entrypoint /bin/bash

    steps:
      - name: id
        run: |
          printenv
          whoami
          pwd
